-- TOURIM complete production database schema
-- Can be used directly with api/install_mysql.php after DB_DRIVER=mysql is configured.
CREATE TABLE IF NOT EXISTS tourim_kv (k VARCHAR(80) PRIMARY KEY, v LONGTEXT NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS roles (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) UNIQUE, permissions JSON NULL, description TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120), email VARCHAR(160) UNIQUE, username VARCHAR(80) UNIQUE, password_hash VARCHAR(255) NOT NULL, role VARCHAR(80) DEFAULT 'admin', status ENUM('active','disabled') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS destinations (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120), slug VARCHAR(160) UNIQUE, country VARCHAR(120), region VARCHAR(120), best_time VARCHAR(160), short TEXT, image VARCHAR(255), status ENUM('published','draft','hidden') DEFAULT 'published', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS packages (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180), slug VARCHAR(220) UNIQUE, destination_id INT NULL, destination VARCHAR(120), duration VARCHAR(80), price DECIMAL(12,2), category VARCHAR(80), short TEXT, itinerary LONGTEXT, inclusions TEXT, exclusions TEXT, image VARCHAR(255), featured BOOLEAN DEFAULT FALSE, status ENUM('published','draft','hidden') DEFAULT 'published', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(destination_id) REFERENCES destinations(id));
CREATE TABLE IF NOT EXISTS hotels (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(180), slug VARCHAR(220) UNIQUE, destination VARCHAR(120), category VARCHAR(80), meal VARCHAR(80), price DECIMAL(12,2), amenities TEXT, image VARCHAR(255), status ENUM('published','draft','hidden') DEFAULT 'published');
CREATE TABLE IF NOT EXISTS blogs (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(200), slug VARCHAR(220) UNIQUE, category VARCHAR(80), author VARCHAR(120), excerpt TEXT, body LONGTEXT, image VARCHAR(255), status ENUM('published','draft','hidden') DEFAULT 'published', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS offers (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180), coupon VARCHAR(80), description TEXT, image VARCHAR(255), valid_until DATE NULL, status ENUM('active','hidden','expired') DEFAULT 'active');
CREATE TABLE IF NOT EXISTS enquiries (id INT AUTO_INCREMENT PRIMARY KEY, public_id VARCHAR(40), name VARCHAR(140), phone VARCHAR(40), email VARCHAR(160), package_name VARCHAR(180), destination VARCHAR(140), travel_date DATE NULL, pax VARCHAR(120), budget VARCHAR(120), country VARCHAR(80), source VARCHAR(80), status ENUM('New','Pending','Replied','Follow-up','Converted','Cancelled') DEFAULT 'New', note TEXT, assigned_to INT NULL, follow_up_date DATE NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bookings (id INT AUTO_INCREMENT PRIMARY KEY, booking_code VARCHAR(80) UNIQUE, customer VARCHAR(160), phone VARCHAR(40), email VARCHAR(160), package_name VARCHAR(180), destination VARCHAR(140), travel_date DATE NULL, pax VARCHAR(80), total_amount DECIMAL(12,2), advance DECIMAL(12,2), balance DECIMAL(12,2), status VARCHAR(60), hotel_plan TEXT, transport_plan TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payments (id INT AUTO_INCREMENT PRIMARY KEY, payment_code VARCHAR(80) UNIQUE, booking_id INT NULL, customer VARCHAR(160), phone VARCHAR(40), package_name VARCHAR(180), amount DECIMAL(12,2), mode VARCHAR(80), transaction_id VARCHAR(160), status VARCHAR(60), payment_date DATE, note TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS invoices (id INT AUTO_INCREMENT PRIMARY KEY, invoice_no VARCHAR(80) UNIQUE, booking_id INT NULL, customer VARCHAR(160), amount DECIMAL(12,2), file_url VARCHAR(255), status VARCHAR(60), generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS vouchers (id INT AUTO_INCREMENT PRIMARY KEY, voucher_no VARCHAR(80) UNIQUE, booking_id INT NULL, customer VARCHAR(160), file_url VARCHAR(255), status VARCHAR(60), generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS analytics_events (id BIGINT AUTO_INCREMENT PRIMARY KEY, event_type VARCHAR(80), item_type VARCHAR(80), item_id VARCHAR(80), title VARCHAR(255), path VARCHAR(255), device VARCHAR(80), metadata JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS media (id INT AUTO_INCREMENT PRIMARY KEY, file_url VARCHAR(255), alt_text VARCHAR(255), type VARCHAR(80), size INT NULL, mime VARCHAR(80), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS whatsapp_templates (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(140), message TEXT, status ENUM('active','hidden') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS seo_routes (id INT AUTO_INCREMENT PRIMARY KEY, route_type VARCHAR(80), slug VARCHAR(220) UNIQUE, target VARCHAR(255), title VARCHAR(255), meta_description TEXT, status ENUM('active','hidden') DEFAULT 'active');
CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id INT NULL, action VARCHAR(120), details TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
